---
title: "Datos-Tanque"
output: html_document
date: "2023-06-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(here)
library(ggplot2)
library(plotrix)
library(segmented)
library(Routliers)
library(tidyverse)
library(ggpubr)
library(car)
```
Experimento Psicoacústico del Tanque

Análisis de datos

#### Datos 1k
```{r Carga Datos 1k, include=FALSE}
Sujetos <- list()
Directorio <- "./Data_1k"

for (i in 1:23) {
  Sujeto <- paste0("Sujeto_", i)
  file_list <- list.files(path = Directorio,
                          pattern =  paste0("^S", i, "_.*\\.csv$"),
                          full.names = TRUE)
  nueva_lista <- bind_rows(lapply(file_list, read_csv)) %>%
    mutate(ID = Sujeto)
  Sujetos[[Sujeto]] <- nueva_lista
}
rm(nueva_lista, file_list, i, Sujeto, Directorio)

# Generamos un solo tibble con toda la información
Datos_1k <- tibble()

for (i in 1:23) {
  nueva_data <-  Sujetos[[i]]  
  Datos_1k <- rbind(Datos_1k, nueva_data) %>%
    mutate(condicion = case_when(
      condicion == 0 ~ "Wide-Wide",
      condicion == 1 ~ "Low-Low",
      condicion == 2 ~ "High-High",
      #condicion == 3 ~ "High-Low",
      #condicion == 4 ~ "Low-High",
      TRUE ~ as.character(condicion)))
}
rm(nueva_data, i, Sujetos)

```

#### Datos 4k

```{r Carga Datos 4k, include=FALSE}
Sujetos <- list()

Directorio <- "./Data_4k"

for (i in 1:23) {
  Sujeto <- paste0("Sujeto_", i+30)
  file_list <- list.files(path = Directorio,
                          pattern =  paste0("^S", i+30, "_.*\\.csv$"),
                          full.names = TRUE)
  nueva_lista <- bind_rows(lapply(file_list, read_csv)) %>%
    mutate(ID = Sujeto)
  Sujetos[[Sujeto]] <- nueva_lista
}
rm(nueva_lista, file_list, i, Sujeto, Directorio)

# Generamos un solo tibble con toda la información

Datos_4k <- tibble()

for (i in 1:23) {
  nueva_data <-  Sujetos[[i]]  
  Datos_4k <- rbind(Datos_4k, nueva_data) %>%
    mutate(condicion = case_when(
      condicion == 0 ~ "Wide-Wide",
      condicion == 1 ~ "Low-Low",
      condicion == 2 ~ "High-High",
      #condicion == 3 ~ "High-Low",
      #condicion == 4 ~ "Low-High",
      TRUE ~ as.character(condicion)))
}
rm(nueva_data, i, Sujetos)

```

#### Limpieza 1k y BP+SL

```{r Limpieza Outliers 1k, warning=FALSE, echo=FALSE}
Datos_1k_BP_cl <- tibble()
conditions = c("Wide-Wide","Low-Low","High-High")
for (condition in conditions) {
  for (Nsujeto in 1:23) {
  
  datos <- Datos_1k %>% filter(grepl(paste0(condition), condicion) & nsub == Nsujeto)

  segmented.rl <- segmented(lm(respuesta ~ distancia, data=datos), seg.Z = ~distancia)
  #print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]))
  {
    # Elimino Outliers
    residuos <- residuals(segmented.rl)
    rango_intercuartilico <- IQR(residuos)
    umbral <- 1.5 * rango_intercuartilico
    indices_outliers <- which(abs(residuos) > umbral)
    
    if (length(indices_outliers)!=0)
  {
datos_sin_outliers <- datos[-indices_outliers, ]
  } else {
  datos_sin_outliers <- datos
  }
    # Calculo de nuevo
    segmented.rl <- segmented(lm(respuesta ~ distancia, data=datos_sin_outliers), seg.Z = ~distancia)
    
    if (!is.null(segmented.rl$psi[2])){
    # Agrego a tibble
    Datos_1k_BP_cl <- rbind(Datos_1k_BP_cl, datos_sin_outliers %>%
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
    summarise(nsub,condicion,bp,slope_dif) %>%
                       unique()
    )
    }
    
  }  else {
    Datos_1k_BP_cl <- rbind(Datos_1k_BP_cl, datos %>%
                  mutate(bp = 0, slope_dif=0) %>%
    summarise(nsub,condicion,slope_dif,bp) %>%
                       unique()
    ) 
    }
  }
}
rm(conditions, condition, indices_outliers,Nsujeto,rango_intercuartilico,residuos,umbral,
   modelo_segmentado,segmented.rl,datos,datos_sin_outliers)
# anova()
# Anova(modelo_segmentado,type=3)
```

#### Limpieza 4k y BP+SL

```{r Limpieza 4k, echo=FALSE, warning=FALSE}
conditions = c("Wide-Wide","Low-Low","High-High")

try_bp <- function(dt) {
    out <- tryCatch(
        {
        segmented(lm(respuesta ~ distancia, data=dt),
                      seg.Z = ~distancia) 
        },
        error=function(cond) {
          segmented.rl <- list()
          segmented.rl$psi[2] <- NULL
            return(segmented.rl)
        }
    )    
    return(out)
}

Datos_4k_BP_cl <- tibble()
for (condition in conditions) {
  for (Nsujeto in 31:53) {
  
  datos <- Datos_4k %>% filter(grepl(paste0(condition), condicion) & nsub == Nsujeto)
  
  segmented.rl <- try_bp(datos)
  
  #print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]))
  {
    # Elimino Outliers
    residuos <- residuals(segmented.rl)
    rango_intercuartilico <- IQR(residuos)
    umbral <- 1.5 * rango_intercuartilico
    indices_outliers <- which(abs(residuos) > umbral)
    
    if (length(indices_outliers)!=0)
  {
datos_sin_outliers <- datos[-indices_outliers, ]
  } else {
  datos_sin_outliers <- datos
  }
    # Calculo de nuevo
    segmented.rl <- segmented(lm(respuesta ~ distancia, data=datos_sin_outliers), seg.Z = ~distancia)
    
    if (!is.null(segmented.rl$psi[2])){
    # Agrego a tibble
    Datos_4k_BP_cl <- rbind(Datos_4k_BP_cl, datos_sin_outliers %>%
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
    summarise(nsub,condicion,bp,slope_dif) %>%
                       unique()
    )
    }
    
  }  else {
    Datos_4k_BP_cl <- rbind(Datos_4k_BP_cl, datos %>%
                  mutate(bp = 0, slope_dif=0) %>%
    summarise(nsub,condicion,slope_dif,bp) %>%
                       unique()
    ) 
    }
  }
  rm(indices_outliers,Nsujeto,rango_intercuartilico,residuos,umbral,modelo_segmentado,segmented.rl,datos,datos_sin_outliers)
}
rm(conditions, condition, indices_outliers,Nsujeto,rango_intercuartilico,residuos,umbral,
   modelo_segmentado,segmented.rl,datos,datos_sin_outliers)
```

#### BP+SL 1k CON OUTLIERS

```{r Calculo BP 1k, include=FALSE}

Datos_1k_BP <- tibble() 

for (Nsujeto in 1:23) {
  
  datos <- Datos_1k %>% filter(grepl(paste0("Wide-Wide"), condicion) & nsub == Nsujeto)

  rl <- lm(respuesta ~ distancia, data=datos)
  segmented.rl <- segmented(rl, seg.Z = ~distancia)
  print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]))
  {
    Datos_1k_BP <- rbind(Datos_1k_BP, datos %>%  
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
                       #group_by(nsub) %>%
                       summarise(nsub,condicion,nsub,slope_dif,bp) %>%
                       unique()
    ) 
    
  }
  #HIGH
  rm(datos,rl,segmented.rl)
  datos <- Datos_1k %>% filter(grepl(paste0("High-High"), condicion) & nsub == Nsujeto)

  rl <- lm(respuesta ~ distancia, data=datos)
  segmented.rl <- segmented(rl, seg.Z = ~distancia)
  print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]))
  {
    Datos_1k_BP <- rbind(Datos_1k_BP, datos %>%  
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
                       #group_by(nsub) %>%
                       summarise(nsub,condicion,nsub,slope_dif,bp) %>%
                       unique()
    ) 
    
  }
  rm(datos,rl,segmented.rl)
  # LOW
  datos <- Datos_1k %>% filter(grepl(paste0("Low-Low"), condicion) & nsub == Nsujeto)

  rl <- lm(respuesta ~ distancia, data=datos)
  segmented.rl <- segmented(rl, seg.Z = ~distancia)
  print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]))
  {
    Datos_1k_BP <- rbind(Datos_1k_BP, datos %>%  
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
                       #group_by(nsub) %>%
                       summarise(nsub,condicion,nsub,slope_dif,bp) %>%
                       unique()
    ) 
    
  }
  rm(datos,rl,segmented.rl)
}

rm(Nsujeto)
```

#### BP+SL 4k CON OUTLIERS

```{r calculo bp 4k, include=FALSE}
Datos_4k_BP <- tibble() 

for (Nsujeto in 31:53) {

  datos <- Datos_4k %>% filter(grepl(paste0("Wide-Wide"), condicion) & nsub == Nsujeto)

  rl <- lm(respuesta ~ distancia, data=datos)
  segmented.rl <- segmented(rl, seg.Z = ~distancia)
  print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]) & !is.na(segmented.rl$coefficients[3]))
  {
    Datos_4k_BP <- rbind(Datos_4k_BP, datos %>%
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
                       #group_by(nsub) %>%
                       summarise(nsub,condicion,nsub,slope_dif,bp) %>%
                       unique()
    )

  }
  #HIGH
  rm(datos,rl,segmented.rl)
  datos <- Datos_4k %>% filter(grepl(paste0("High-High"), condicion) & nsub == Nsujeto)

  rl <- lm(respuesta ~ distancia, data=datos)
  segmented.rl <- segmented(rl, seg.Z = ~distancia)
  print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]) & !is.na(segmented.rl$coefficients[3]))
  {
    Datos_4k_BP <- rbind(Datos_4k_BP, datos %>%
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
                       #group_by(nsub) %>%
                       summarise(nsub,condicion,nsub,slope_dif,bp) %>%
                       unique()
    )

  }
  rm(datos,rl,segmented.rl)

  # LOW
  if(Nsujeto!=45)
  {
  datos <- Datos_4k %>% 
    filter(grepl(paste0("Low-Low"), condicion) & nsub == Nsujeto)

  rl <- lm(respuesta ~ distancia, data=datos)
  segmented.rl <- segmented(rl, seg.Z = ~distancia)
  print(segmented.rl$psi[2])
  if (!is.null(segmented.rl$psi[2]) & !is.na(segmented.rl$coefficients[3]))
  {
    Datos_4k_BP <- rbind(Datos_4k_BP, datos %>%
                       mutate(bp = segmented.rl$psi[2], slope_dif=segmented.rl$coefficients[3] ) %>%
                       #group_by(nsub) %>%
                       summarise(nsub,condicion,nsub,slope_dif,bp) %>%
                       unique()
    )

  }
   rm(datos,rl,segmented.rl)

  }
}
rm(Nsujeto)
```

#### Grafico BPs

```{r Boxplot BPs, echo=FALSE}

plt_1k_bp <- ggplot(Datos_1k_BP_cl %>% filter(bp!=0), aes(x=condicion, y=bp, color=condicion)) +
  geom_boxplot()+
  labs(title="1k")+
  theme_minimal()
plt_1k_bp

plt_4k_bp <- ggplot(Datos_4k_BP_cl %>% filter(bp!=0), aes(x=condicion, y=bp, color=condicion)) + 
  geom_boxplot()+
  labs(title="4k")+
  theme_minimal()
plt_4k_bp

ggarrange(plt_1k_bp,plt_4k_bp, common.legend = TRUE)
```

#### T-test de BPs


```{r, echo=TRUE}

Wide_1k_bp <- Datos_1k_BP_cl %>% filter(condicion=="Wide-Wide") %>% filter(bp!=0)
Low_1k_bp <-Datos_1k_BP %>% filter(condicion=="Low-Low") %>% filter(bp!=0)
High_1k_bp <- Datos_1k_BP %>% filter(condicion=="High-High")%>% filter(bp!=0)

Wide_4k_bp <- Datos_4k_BP %>% filter(condicion=="Wide-Wide")%>% filter(bp!=0)
Low_4k_bp <-Datos_4k_BP %>% filter(condicion=="Low-Low")%>% filter(bp!=0)
High_4k_bp <- Datos_4k_BP %>% filter(condicion=="High-High")%>% filter(bp!=0)

t.test(x = Wide_1k_bp$bp, Low_1k_bp$bp)
t.test(x = Wide_1k_bp$bp, High_1k_bp$bp)

t.test(x = Wide_1k_bp$slope_dif, Low_1k_bp$slope_dif)
t.test(x = Wide_1k_bp$slope_dif, High_1k_bp$slope_dif)

t.test(x = Wide_4k_bp$bp, Low_4k_bp$bp)
t.test(x = Wide_4k_bp$bp, High_4k_bp$bp)

t.test(x = Wide_4k_bp$slope_dif, Low_4k_bp$slope_dif)
t.test(x = Wide_4k_bp$slope_dif, High_4k_bp$slope_dif)

t.test(x = Wide_4k_bp$slope_dif, subset(Low_4k_bp$slope_dif, Low_4k_bp$slope_dif>-6))
```
#### Grafico Slopes

```{r}

plt_1k_slope_dif <- ggplot(Datos_1k_BP_cl%>% filter(bp!=0), aes(x=condicion, y=slope_dif, color=condicion)) + 
  geom_boxplot()+
  labs(title="Slopes 1k")+
  theme_minimal()
#plt_1k_bp

plt_4k_slope_dif <- ggplot(Datos_4k_BP_cl%>% filter(bp!=0), aes(x=condicion, y=slope_dif, color=condicion)) + 
  geom_boxplot()+
  labs(title="Slopes 4k")+
  theme_minimal()
#plt_4k_bp

ggarrange(plt_1k_slope_dif,plt_4k_slope_dif, common.legend = TRUE)

```

#### Pruebas de quita de Outliers para regresiones lineales simples

```{r}
Datos_1k_cl <- tibble()
Datos_1k_ols <- tibble() %>% mutate(nsub=0,distancia=0, respuesta=0)
Conditions = c("Low-Low", "Wide-Wide", "High-High")
for (Nsujeto in 1:23){
  for (cond in Conditions){
  datos <- Datos_1k %>% 
    filter(grepl(paste0(cond), condicion) & nsub == Nsujeto) %>%
    mutate(distancia=log(distancia), respuesta=log(respuesta))
  
    outliers_datos <- outliers_mcd(x=cbind(datos$distancia,datos$respuesta), h=.75)
    datos_sinOutliers <- datos
    for (i in 1:length(outliers_datos$outliers_val$X1)){
      datos_sinOutliers <- datos_sinOutliers %>%     filter(distancia!=outliers_datos$outliers_val$X1[i] | respuesta!=outliers_datos$outliers_val$X2[i])
      
      Datos_1k_ols <- Datos_1k_ols %>% add_row(nsub=Nsujeto, distancia=outliers_datos$outliers_val$X1[i], 
respuesta=outliers_datos$outliers_val$X2[i])
    }
    Datos_1k_cl <- rbind(Datos_1k_cl,datos_sinOutliers)
  }
}

rm(cond,Conditions,i,Nsujeto,rl,segmented.rl,outliers_datos,datos_sinOutliers, datos)
```
```{r}
plt_1k_cl <- ggplot(Datos_1k_cl, aes(x=distancia,
                               y=respuesta,
                               color = condicion)) +
  geom_point() +
  geom_smooth(method=lm, se = FALSE) +
  # scale_x_log10() +
  # scale_y_log10() +
  #geom_errorbar(aes(ymin=respuesta-std, ymax=respuesta+std), width = 0.2) +
  # facet_grid(rows = vars(ID)) +
  labs(title = "Curva de Distancia",
  #subtitle = "Promedio y Barras de Error",
       x = 'Distancia',
       y = 'Respuesta') +
  theme_classic()
plt_1k_cl




```

```{r}
datos <- Datos_4k %>% 
    filter(grepl(paste0("Low-Low"), condicion) & nsub == 45) %>%
    mutate(distancia=log(distancia), respuesta=log(respuesta))

outliers_datos <- outliers_mcd(x=cbind(datos$distancia,datos$respuesta), h=.75)
outliers_datos
plot_outliers_mcd(outliers_datos, x=cbind(datos$distancia,datos$respuesta))

rl <- lm(respuesta ~ distancia, data=datos)
summary(rl)  

plot <- ggplot(data=datos, aes(x=distancia, y=respuesta)) +
    geom_point() +
    geom_smooth(method=lm, se = FALSE)
plot

datos_sinOutliers <- datos
for (i in 1:length(outliers_datos$outliers_val$X1)){
  datos_sinOutliers <- datos_sinOutliers %>% filter(distancia!=outliers_datos$outliers_val$X1[i] | respuesta!=outliers_datos$outliers_val$X2[i])
}

rl <- lm(respuesta ~ distancia, data=datos_sinOutliers)
summary(rl)  

plot <- ggplot(data=datos, aes(x=distancia, y=respuesta)) +
    geom_point() +
    geom_smooth(method=lm, se = FALSE)
plot


segmented.rl <- segmented(rl, seg.Z = ~distancia)
summary(segmented.rl)

```




#### Ejemplo Limpieza BP
```{r}

datos <- Datos_4k %>% filter(grepl(paste0("Low-Low"), condicion) & nsub == 46)

# Realizar la regresión segmentada

segmented.rl <- segmented(lm(respuesta ~ distancia, data = datos), seg.Z = ~ distancia)

segmented.rl <- try_bp(datos)

# Obtener los residuos del modelo segmentado
residuos <- residuals(modelo_segmentado)

# Calcular el rango intercuartílico de los residuos
rango_intercuartilico <- IQR(residuos)

# Definir un umbral para detectar outliers
umbral <- 1.5 * rango_intercuartilico

# Identificar los índices de los outliers
indices_outliers <- which(abs(residuos) > umbral)

# Eliminar los outliers del conjunto de datos original
datos_sin_outliers <- datos[-indices_outliers, ]

modelo_segmentado <- segmented(lm(respuesta ~ distancia, data = datos_sin_outliers), seg.Z = ~ distancia)


plot(datos_sin_outliers$distancia, datos_sin_outliers$respuesta, pch=16, col='steelblue', log="xy")
plot(lm(respuesta ~ distancia, data = datos_sin_outliers), add=T)

observaciones_diferentes <- setdiff(as.data.frame(datos), as.data.frame(datos_sin_outliers))
```
